### ISSUE TITLE
Frustrating update experience

### ISSUE THREAD

**Issue by curtisblackwell** [beyondcode/tinkerwell-suggestions#191]
This seems to happen every time I update:

1. Trigger update
2. Get this message and quit app
3. Re-open app
4. Get this message again and quit app
5. Wait a few minutes and re-open app
6. Get this message

![image](https://user-images.githubusercontent.com/468029/79470828-7b2d3080-7fc7-11ea-9785-e6cdc6d08f80.png)

It would be great if a more typical app update experience was used. Most apps seem to show a dialog to exit, update, and automatically re-open the app.

**Comment by sschlein** [comment]
This has been fixed in 2.6

https://tinkerwell.app/release/2.6.0

**Comment by curtisblackwell** [comment]
Trying to update from 2.7.0 to 2.8.3 and this still happens, just with a different dialog.

**Comment by cbaconnier** [comment]
I'm still experiencing this issue with the version 2.8.0
I uninstalled it when I had the version 2.6 and re-installed 2.8.0 using `AppImage` 
I'm still getting the message and doesn't update to 2.8.3

> Tinkerwell is ready to update. Please quit the app and restart it to trigger the update process.

I'm using Ubuntu 18.04

**Comment by sschlein** [comment]
Can you use download for 2.8.3 directly?

**Comment by curtisblackwell** [comment]
I did. Just letting you know the fix doesn't seem to be working.

**Comment by mikeerickson** [comment]
I have never once had a update work, I have always had to download the full app archive.  Be careful to copy any existing code you might have using Tinkerwell, as you are likely to lose everything when you upgrade.

**Comment by cbaconnier** [comment]
@sschlein 
> Can you use download for 2.8.3 directly?

I can download/update manually. But it would be great to have the automatic update working as expected.

**Comment by sschlein** [comment]
@cbaconnier 
The problem is that we are using the standard Electron way to do this and have even wrapped this process into a fallback that works for most people. I have no ad-hoc solution to this problem.

**Comment by cbaconnier** [comment]
Too bad :(
I have never worked with Electron before, but is there something we can do to help with this?

**Comment by rossco555** [comment]
Updating to 2.23.0 right now and I agreed to it thinking it was a 5min job. 30mins and counting, but the progress bar is certainly moving ever so slightly.

**Comment by cbaconnier** [comment]
> Updating to 2.23.0 right now and I agreed to it thinking it was a 5min job. 30mins and counting, but the progress bar is certainly moving ever so slightly.

Is this happened to every last updates? 
I know that @mechelon did an excellent work with the updater this year: https://github.com/beyondcode/tinkerwell-community/issues/314#issuecomment-1008693112  
I didn't got any issues since then in both Ubuntu/Manjaro. 
Could it be an unrelated issue? That doesn't sound similar to the issue we were all having.
