### ISSUE TITLE
Settings wont save (Windows 10)

### ISSUE THREAD

**Issue by K2ouMais** [beyondcode/tinkerwell-suggestions#68]
Should "Fira Code" be the default font? Well it isnt.

Go to the settings, change the font to another font and back to "Fira Code" and you will see the difference. Take a look on the ligatures of the font , that at first arent there.

The same goes to "Working Directory". I have to set it everytime I open Tinkerwell.

I have this problem on 2 different PCs.

Here is an example:
https://youtu.be/1MpllT6E2Ww

Both of my PCs have a fully updated Windows 10.

**Comment by sschlein** [comment]
Should be fixed with the recent release that we deployed a few minutes ago - you get it on app restart automatically

**Comment by K2ouMais** [comment]
The font problem persists on the right side. (Output side)

On the left side the font stay like in the settings.
